import { SaleRecord } from "../types";

export const analyzeSalesData = async (records: SaleRecord[]): Promise<string> => {
  if (!records || records.length === 0) {
    return "No sales records available for analysis.";
  }
  
  // Create a streamlined dataset for the AI
  const salesSummary = records.map(r => ({
    date: r.date,
    crop: r.cropType,
    qty: `${r.unitsSold} ${r.unitType}`,
    price: r.unitPrice,
    total: r.totalSale,
    cluster: r.cluster || 'Unassigned',
    farmer: r.farmerName,
    customer: r.customerName
  }));

  const prompt = `
    Analyze the following agricultural sales records from our cooperative.
    
    Please generate a professional audit report in Markdown format.
    
    Your report should include:
    1. **Executive Summary**: A brief overview of the sales volume and revenue.
    2. **Food Coop Performance**: Compare sales activity across different food coops.
    3. **Pricing Analysis**: Identify any pricing inconsistencies or anomalies for similar crops.
    4. **Key Insights**: Highlight top-performing farmers, frequent buyers, or unusual trends.
    5. **Recommendations**: Strategic advice for the cooperative management.

    DO NOT include any signatures, watermarks, or phrases like "Generated by Gemini" in your response.

    Sales Data (JSON):
    ${JSON.stringify(salesSummary, null, 2)}
  `;

  try {
    const response = await fetch('/api/gemini', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json'
        },
        body: JSON.stringify({
           prompt,
           model: 'gemini-3.5-flash',
           systemInstruction: "You are an expert agricultural economist and cooperative auditor. Provide data-driven insights with a professional tone.",
           temperature: 0.3
        })
    });

    if (!response.ok) {
         const err = await response.json();
         throw new Error(err.error || 'Failed to generate report');
    }

    const data = await response.json();

    return data.text || "No analysis generated.";
  } catch (error) {
    console.error("Gemini Analysis Error:", error);
    return `Error generating AI report: ${error instanceof Error ? error.message : "Unknown error"}`;
  }
};

export const generateAgroecologyProfile = async (homesteadName: string, farmName: string, lat: number, lng: number): Promise<string> => {
  try {
    const isKenya = lat >= -4.72 && lat <= 4.62 && lng >= 33.9 && lng <= 41.9;

    let soilMoistureData = 'Retrieving from OpenEPI via Satellite... (simulated API delay check)';
    let soilStaticData = '';

    if (isKenya) {
      soilStaticData = 'Provider: RCMRD (Regional Data). Expected Type: Nitosols/Ferralsols. Expected pH: 5.5 - 6.5 (Simulated API Pull)';
    } else {
      soilStaticData = 'Provider: SoilGrids (Global Fallback). Evaluated general parameters. (Simulated API Pull)';
    }

    const dataStrategySource = isKenya 
      ? `For Soil Moisture (Dynamic): Satellite Radar API (OpenEPI / Sentinel-1).
For pH and Soil Type (Static): Local Providers (Cropnuts / RCMRD) for high-accuracy regional data.`
      : `For Soil Moisture (Dynamic): Satellite Radar API (OpenEPI / Sentinel-1).
For pH and Soil Type (Static): SoilGrids (Global Baseline). Note: Recommend the integration of local providers for more accurate data in this region.`;

    const prompt = `You are the Cooppesa Agroecology AI Engine.
Generate a detailed Agroecology Profile for a farm plot located at coordinates (${lat.toFixed(4)}, ${lng.toFixed(4)}).
The homestead is "${homesteadName}" and the plot is "${farmName}".

Data Sourcing Strategy for this Request:
${dataStrategySource}

Current API Data Context:
- Soil Moisture: ${soilMoistureData}
- Soil Physical Static Data: ${soilStaticData}

Provide:
1. **Soil Information Strategy & Estimates**: Explicitly state the data sourcing strategy used. Provide the expected soil type, pH, and live moisture estimates based on the API Data Context provided above.
2. **Detailed Agroecology Recommendations** (crops to plant, soil management, water harvesting). Recommend a wide window of food crops depending on the soil data, including indigenous food crops and crops common to the region in question. Give farmers a variety of options to select from. Also consider if the climate and soil can support: tomatoes, kales, cabbage, rice, specific types of beans, groundnuts, maize, yam, cassava, potatoes, bananas, watermelon, etc. Do not hallucinate, rely strictly on agricultural truth for the given coordinates.
3. **A Suggested Seasonal Calendar** (management of inputs and harvest).
Ensure it is formatted using clean Markdown. Focus on regenerative agriculture and climate resilience. Keep it concise but comprehensive.`;

    const response = await fetch('/api/gemini', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json'
        },
        body: JSON.stringify({
           prompt,
           model: 'gemini-3.5-flash',
           systemInstruction: "You are an expert Agroecology AI.",
           temperature: 0.7
        })
    });

    if (!response.ok) {
         const err = await response.json();
         throw new Error(err.error || 'Failed to generate profile');
    }

    const data = await response.json();
    return data.text || "No profile generated.";
  } catch (error) {
    console.error("Error generating agroecology profile:", error);
    return "Agroecology analysis is currently unavailable. Please try again later.";
  }
};
